### ISSUE TITLE
22165 Team Members Carousel Position style  is not getting applied 

### ISSUE THREAD

**Issue by vipulc2** [helloideabox/powerpack-lite-elementor#20]
**Describe the Bug**
The style for the Position text of the Team Member carousel is not getting any style applied to it in the frontend. Style options like Typography, color are not working in the frontend.

![image](https://user-images.githubusercontent.com/61476520/117617853-bda14c80-b18a-11eb-9eb2-cdff20bbe11f.png)

**Comment by simrandeep** [comment]
Fixed
