### ISSUE TITLE
23437 Posts widget Pagination issue

### ISSUE THREAD

**Issue by vipulc2** [helloideabox/powerpack-lite-elementor#24]
**Describe the Bug**
Posts widget has the issue where the pagination(without AJAX) is not working.

![image](https://user-images.githubusercontent.com/61476520/127311585-9f804cae-f25a-493c-a411-bc82f4fd7ff1.png)

**Comment by simrandeep** [comment]
Fixed

**Comment by Michaelgimii** [comment]
Hi @simrandeep , Can we report a critical bug in the powerpack plugin here? Or open a new request?

**Comment by simrandeep** [comment]
Hi @Michaelgimii, Please open a new request.
